Python/Django/project-test/mysite-project/books/urls.py
from django.conf.urls import url
from django.contrib import admin
from books import views

urlpatterns = [
	url( r'^$', views.BooksModelView.as_view(), name='index' ),
	
	url( r'^book/$', views.BookList.as_view(), name = 'book_list' ),
	url( r'^author/$', views.AuthorList.as_view(), name = 'author_list' ),
	url( r'^publisher/$', views.PublisherList.as_view(), name = 'publisher_list' ),
	
	url( r'^book/(?P<pk>\d+)/$', views.BookDetail.as_view(), name = 'book_detail' ),
	url( r'^author/(?P<pk>\d+)$', views.AuthorDetail.as_view(), name = 'author_detail' ),
	url( r'^publisher/(?P<pk>\d+)$', views.PublisherDetail.as_view(), name = 'publisher_detail' ),
]

Python/Django/project-test/mysite-project/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from mysite import views

urlpatterns = [
    url( r'^$', views.HomeView.as_view(), name = 'home' ),
    url( r'^polls/', include( 'polls.urls', namespace = "polls" ) ),
    url( r'^books/', include( 'books.urls', namespace = "books" ) ),
    url( r'^admin/', include( admin.site.urls ) ),
]

Python/Django/project-test/mysite-project/books/models.py
from django.db import models

# Create your models here.
class Book( models.Model ):
    title = models.CharField( max_length = 100 )
    authors = models.ManyToManyField( 'Author' )
    publisher = models.ForeignKey( 'Publisher' )
    publication_date = models.DateField()

    def __str__( self ):
        return self.title

class Author( models.Model ):
    salutation = models.CharField( max_length = 100 )
    name = models.CharField( max_length = 50 )
    email = models.EmailField()

    def __str__( self ):
        return self.name

class Publisher( models.Model ):
    name = models.CharField( max_length = 100 )
    address = models.CharField( max_length = 100 )
    website = models.URLField()

    def __str__( self ):
        return self.name

Python/Django/project-test/mysite-project/polls/models.py
from django.db import models

# Question Table
#	Coulmn			Type			Django Var				Django Filed Class
#	 id				 integer		 ( question_id )		 ( PK 는 Django 에서 자동 생성 )
#	 question_text	 varchar(200)	 question_text			 models.CharFiled( max_length = 200 )
#	 pub_date		 datetime		 pub_date				 models.DateTimeFiled( 'date published' )
class Question( models.Model ):
	question_text = models.CharField( max_length = 200 )
	pub_date = models.DateTimeField( 'date published' )

	def __str__( self ): # __unicode__ on Python 2
		sStr = str( [ self.question_text, self.pub_date ] )
		return sStr

class Choice( models.Model ):
    # FK 는 항상 다른 테이블의 PK 만 연결되므로 Question 클래스의 question_id 까지 지정할 필요가 없다.
	question = models.ForeignKey( Question )
	choice_text = models.CharField( max_length = 200 )
	votes = models.IntegerField( default = 0 )

	def __str__( self ):
		sStr = str( [ self.choice_text, self.votes ] )
		return sStr

# Create your models here.

Python/Django/project-test/mysite-project/books/views.py
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from books.models import Book, Author, Publisher

# Create your views here.

# TemplateView
class BooksModelView( TemplateView ):
    template_name = 'books/index.html'

    def get_context_data( self, **kwargs ):
        context = super( BooksModelView, self ).get_context_data( **kwargs )
        context['object_list'] = ['Book', 'Author', 'Publisher']
        return context


# ListView
class BookList( ListView ):
    model = Book

class AuthorList( ListView ):
    model = Author

class PublisherList( ListView ):
    model = Publisher


# DetailView
class BookDetail( DetailView ):
    model = Book

class AuthorDetail( DetailView ):
    model = Author

class PublisherDetail( DetailView ):
    model = Publisher

Python/Django/project-test/mysite-project/mysite/views.py
from django.views.generic.base import TemplateView

#-- TemplateView
class HomeView( TemplateView ):
    template_name = 'home.html'

    def get_context_data( self, **kwargs ):
        context = super( HomeView, self ).get_context_data( **kwargs )
        context['object_list'] = ['polls', 'books']
        return context

Python/Django/project-test/mysite-project/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from polls.models import Choice, Question

import logging

#logging
gLogger = logging.getLogger( __name__ )

def index( aRequest ):
	lastest_question_list = Question.objects.all().order_by( '-pub_date' )[:5]
	sContext = { 'lastest_question_list': lastest_question_list }
	return render( aRequest, 'polls/index.html', sContext )

def detail( aRequest, aQuestion_id ):
	sQuestion = get_object_or_404( Question, pk = aQuestion_id )
	return render( aRequest, 'polls/detail.html', { 'question': sQuestion } )

def vote( aRequest, aQuestion_id ):
	gLogger.debug( "vote().question_id: %s" % aQuestion_id )
	
	sP = get_object_or_404( Question, pk = aQuestion_id )
	try:
		sSelect_choice = sP.choice_set.get( pk = aRequest.POST['choice'] )
	except ( KeyError, Choice.DoesNotExist ):
		return render( aRequest, 'polls/detail.html',
		{ 'question' : sP,
		'error_message': "You didn`t select a choice." 
		} )
	else:
		sSelect_choice.votes += 1
		sSelect_choice.save()
		return HttpResponseRedirect( reverse( 'polls:results', args = ( sP.id, )))

def results( aRequest, aQuestion_id ):
	sQuestion = get_object_or_404( Question, pk = aQuestion_id )
	return render( aRequest, 'polls/results.html', {'question': sQuestion } )

Python/Django/project-test/mysite-project/books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.salutation }}</p>
<li>Email : {{ object.email }}</li>
{% endblock content %}

Python/Django/project-test/mysite-project/books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list %}
            <li><a href = "{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

Python/Django/project-test/mysite-project/books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <br>
    <li>Authors:
        {% for author in object.authors.all %}
            {{author }}
            {% if not forloop.last %},{% else %}{% endif %}
        {% endfor %}
    </li>
    <li>Publisher: {{ object.publisher }}</li>
    <li>Publication date : {{ object.publication_date }}</li>
{% endblock content %}

Python/Django/project-test/mysite-project/books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href = "{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

Python/Django/project-test/mysite-project/books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Books Management System</h2>
    <ul>
        {% for modelname in object_list %}
            {# urlvar 에 books:modelname_list 를 저장. modelname_list 가 authur 라면 books:authur_list 가 urlvar 에 저장된다. #}
            {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
                <li><a href="{% url urlvar %}">{{modelname}}</a></li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}
        

Python/Django/project-test/mysite-project/books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.website }}</p>
<li>Address : {{ object.address }}</li>
{% endblock content %}

Python/Django/project-test/mysite-project/books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href = "{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

Python/Django/project-test/mysite-project/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action = "{% url 'polls:vote' question.id %}" method = "post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type = "radio" name = "choice" id = "choice{{ forloop.counter }}" value = "{{ choice.id }}" />
        <label for "choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type = "submit" value = "Vote" />
</form>

Python/Django/project-test/mysite-project/polls/templates/polls/index.html
{% if lastest_question_list %}
	<ul>
	{% for question in lastest_question_list %}
		<li><a href = "/polls/{{question.id}}/">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

Python/Django/project-test/mysite-project/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} - {{ choice.votes }} 
        vote{{ choice.votes | pluralize }}</li>
{% endfor %}
</ul>

<a href = "{% url 'polls:detail' question.id %}">Vote again?</a>

Python/Django/project-test/mysite-project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel = "stylesheet" href="{% static "admin/css/base.css" %}" />"
    <title>{% block title %}My Amazing Site{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
            <ul>
                <li><a href = "/">Project_Home</a></li>
                <li><a href = "/admin/">Admin</a></li>
            </ul>   
        {% endblock %}
        <br>
    </div>

    <div id = "content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

Python/Django/project-test/mysite-project/templates/base_books.html
{% extends "base.html" %}

<title>{% block title %}Books Application Site{% endblock %}</title>

{% block sidebar %}
{{ block.super }}
<ul>
    <li><a href = "/books/">Books_Home</a></li>
</ul>
{% endblock %}

Python/Django/project-test/mysite-project/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h2>My Django Applications</h2>
    <ul>
        {% for appname in object_list %}
            {% with appname|add:":"|add:"index" as urlval %}
                <li><a href = "{% url urlvar %}">{{ appname }}</a></li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}